name: awesome_aurora_gradient
description: A very colourful extension to create awesome Aurora gradients.
version: 0.3.0+2
homepage: https://github.com/vento007/awesome_aurora_gradient

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

